package org.exalt.cssr.reservations;

import org.exalt.cssr.cars.Car;
import org.reservations.cssr.CarSoap;
import org.reservations.cssr.ReservationSoap;
import org.reservations.cssr.ReservationStatusSoap;
import org.springframework.stereotype.Service;

import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDateTime;

/**
 * Map between the original Reservation entity and ReservationSoap
 */
@Service
public class ReservationMapper {
    /**
     * Mapping between the original entity and the soap entity
     * @param reservation the original entity
     * @return reservationSoap that generated by the jaxb plugin
     */
    public ReservationSoap mapReservationToReservationSoap(Reservation reservation) {
        return ReservationSoap.builder()
                .id(reservation.getId())
                .carId(reservation.getCarId())
                .startTime(mapLcaLocalDateTimeToXMLGregorianCalendar(reservation.getStartTime()))
                .endTime(mapLcaLocalDateTimeToXMLGregorianCalendar(reservation.getEndTime()))
                .reservationStatus(ReservationStatusSoap.fromValue(reservation.getStatus().name()))
                .driverId(reservation.getDriverId())
                .build();
    }

    /**
     * Map from LocalDateTime to XMLGregorianCalendar
     * @param localDateTime LocalDateTime
     * @return XMLGregorianCalendar
     */
    private XMLGregorianCalendar mapLcaLocalDateTimeToXMLGregorianCalendar(LocalDateTime localDateTime){
       return DatatypeFactory.newDefaultInstance().newXMLGregorianCalendar(localDateTime.toString());
    }

}
