package org.exalt.cssr.cars;

import org.reservations.cssr.CarSoap;
import org.springframework.stereotype.Service;

/**
 * Map between the original Car entity and CarSoap
 */
@Service
public class CarMapper {
    /**
     * Mapping between the original entity and the soap entity
     * @param car the original entity
     * @return CarSoap that generated by the jaxb plugin
     */
    public CarSoap mapCarToCarSoap(Car car) {
        return CarSoap.builder()
                .id(car.getId())
                .ownerId(car.getOwnerId())
                .model(car.getModel())
                .make(car.getMake())
                .year(car.getYear())
                .available(car.isAvailable())
                .hourlyRate(car.getHourly_rate())
                .build();
    }
}
