package org.exalt.cssr.cars;

import org.reservations.cssr.CarSoap;
import org.springframework.stereotype.Service;

/**
 * Map between the original Car entity and CarSoap
 */
@Service
public class CarMapper {
    /**
     * Mapping between the original entity and the soap entity
     *
     * @param car the original entity
     * @return CarSoap that generated by the jaxb plugin
     */
    public CarSoap mapCarToCarSoap(Car car) {
        CarSoap carSoap = new CarSoap();
        carSoap.setId(car.getId());
        carSoap.setOwnerId(car.getOwnerId());
        carSoap.setModel(car.getModel());
        carSoap.setMake(car.getMake());
        carSoap.setYear(car.getYear());
        carSoap.setAvailable(car.isAvailable());
        carSoap.setHourlyRate(car.getHourly_rate());
        return carSoap;
    }
}
